[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flask-app"
version = "0.1.0"
description = "Flask backend app"
dependencies = [
    "flask"
]

[tool.setuptools.packages.find]
where = ["."]
